[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "protein-mutation-impact"
version = "0.0.0"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]
